[package]
name = "vote_manager"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc4", path = "../ink/crates/primitives", default-features = false }
ink_metadata = { version = "3.0.0-rc4", path = "../ink/crates/metadata", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc4", path = "../ink/crates/env", default-features = false }
ink_prelude = { version = "3.0.0-rc4", path = "../ink/crates/prelude", default-features = false }
ink_storage = { version = "3.0.0-rc4", path = "../ink/crates/storage", default-features = false }
ink_lang = { version = "3.0.0-rc4", path = "../ink/crates/lang", default-features = false }

scale = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }

funty="=1.1.0"

vault = { version = "0.1.0", path = "../vault", default-features = false, features = ["ink-as-dependency"] }
auth = { version = "0.1.0", path = "../auth", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "vote_manager"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",

    "vault/std",
    "auth/std",
]
ink-as-dependency = []
